// Generated by Selenium IDE
import java.io.File;
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class APruebaImportacionIT {
  private WebDriver driver;
  JavascriptExecutor js;
  
  @Before
  public void setUp() {
	//System.setProperty("webdriver.chrome.driver","./src/test/resources/drivers/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void prueba() {
	File titulacion = new File("Titulacion.xlsx");
	File alumnos = new File("alumnos.xlsx");
	File asignaturas = new File("Oferta_asignaturas.xlsx");
	File grupos = new File("grupos.xlsx");
	File encuesta = new File("Encuesta.xlsx");
    driver.get("http://localhost:8080/ProyectoWAR/");
    driver.manage().window().maximize();
    driver.findElement(By.linkText("Importar")).click();
    driver.findElement(By.id("Importaciones:Alumnos")).sendKeys(alumnos.getAbsolutePath());
    driver.findElement(By.id("Importaciones:Titulaciones")).sendKeys(titulacion.getAbsolutePath());
    driver.findElement(By.id("Importaciones:Asignaturas")).sendKeys(asignaturas.getAbsolutePath());
    driver.findElement(By.id("Importaciones:Grupos")).sendKeys(grupos.getAbsolutePath());
    driver.findElement(By.id("Importaciones:Encuestas")).sendKeys(encuesta.getAbsolutePath());
    driver.findElement(By.id("Importaciones:submit")).click();
    try {
        Thread.sleep(5000);
    } catch (Exception e) {
        System.out.println(e);
    }

    driver.findElement(By.linkText("Home")).click();
    {
       List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(1) > td:nth-child(1)"));
       assert(elements.size() > 0);
    }
  }
}