// Generated by Selenium IDE
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
public class BuscarTitulacionIT {
  private WebDriver driver;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver","./src/test/resources/drivers/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void prueba() {
    driver.get("http://127.0.0.1:8080/ProyectoWAR/");
    driver.manage().window().maximize();
    driver.findElement(By.id("form:titulacion")).click();
    driver.findElement(By.id("form:titulacion")).sendKeys("Grado en Ingeniería del Software");
    driver.findElement(By.id("form:search")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(4)")).click();
    //Dormimos para que de tiempo a recargar la página ya que con
    //driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS); no funciona
    try {
        Thread.sleep(5000);
    } catch (Exception e) {
        System.out.println(e);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(1) > td:nth-child(4)"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(4)")).getText(), is("Grado en Ingeniería del Software"));
  }
}
