// Generated by Selenium IDE
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class BuscarAlumnoIT {
  private WebDriver driver;
  JavascriptExecutor js;
  
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void dada() {
    driver.get("http://localhost:8080/ProyectoWAR/");
    driver.manage().window().maximize();
    driver.findElement(By.id("form:name")).click();
    driver.findElement(By.id("form:name")).sendKeys("Rocco");
    driver.findElement(By.id("form:search")).click();
  }
}
