// Generated by Selenium IDE
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class ModificarAsignaturaIT {
  private WebDriver driver;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver","./src/test/resources/drivers/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void prueba() {
    driver.get("http://127.0.0.1:8080/ProyectoWAR/");
    driver.manage().window().maximize();
    driver.findElement(By.linkText("Asignaturas")).click();
    driver.findElement(By.id("frm:asignaturas:1:__edit")).click();
    try {
        Thread.sleep(7000);
    } catch (Exception e) {
        System.out.println(e);
    }
    driver.findElement(By.id("asig-form:idiomas")).clear();
    driver.findElement(By.id("asig-form:idiomas")).sendKeys("Inglés");
    driver.findElement(By.id("asig-form:sendAsig")).click();
    try {
        Thread.sleep(3000);
    } catch (Exception e) {
        System.out.println(e);
    }
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(9)")).getText(), is("Inglés"));
    driver.findElement(By.id("frm:asignaturas:1:__edit")).click();
    try {
        Thread.sleep(5000);
    } catch (Exception e) {
        System.out.println(e);
    }
    driver.findElement(By.id("asig-form:idiomas")).clear();
    driver.findElement(By.id("asig-form:sendAsig")).click();
  }
}
