// Generated by Selenium IDE
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class ModificarExpedienteIT {
  private WebDriver driver;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	//System.setProperty("webdriver.chrome.driver","./src/test/resources/drivers/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    //driver.quit();
  }
  @Test
  public void prueba() {
    driver.get("http://127.0.0.1:8080/ProyectoWAR/#");
    driver.manage().window().maximize();
    driver.findElement(By.id("matriculas:0:_exp")).click();
    try {
        Thread.sleep(7000);
    } catch (Exception e) {
        System.out.println(e);
    }
    driver.findElement(By.id("exp-form:media")).clear();
    driver.findElement(By.id("exp-form:media")).sendKeys("8.5");
    driver.findElement(By.id("exp-form:sendExp")).click();
    driver.findElement(By.id("matriculas:0:_exp")).click();
    try {
        Thread.sleep(7000);
    } catch (Exception e) {
        System.out.println(e);
    }
    {
      String value = driver.findElement(By.id("exp-form:media")).getAttribute("value");
      assertThat(value, is("8.5"));
    }
    driver.findElement(By.id("exp-form:media")).clear();
    driver.findElement(By.id("exp-form:media")).sendKeys("3");
    driver.findElement(By.cssSelector("#id01 .w3-button")).click();
    driver.findElement(By.id("matriculas:0:_exp")).click();
    try {
        Thread.sleep(7000);
    } catch (Exception e) {
        System.out.println(e);
    }
    {
      String value = driver.findElement(By.id("exp-form:media")).getAttribute("value");
      assertThat(value, is("8.5"));
    }
    driver.findElement(By.id("exp-form:media")).clear();
    driver.findElement(By.id("exp-form:media")).sendKeys("0.0");
    driver.findElement(By.id("exp-form:sendExp")).click();
  }
}
