// Generated by Selenium IDE
import org.junit.Test;

import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ModificarMatriculaIT {
  private WebDriver driver;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	//System.setProperty("webdriver.chrome.driver","./src/test/resources/drivers/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void prueba() {
    driver.get("http://127.0.0.1:8080/ProyectoWAR/");
    driver.manage().window().maximize();
    driver.findElement(By.id("matriculas:0:_mat")).click();
    try {
        Thread.sleep(7000);
    } catch (Exception e) {
        System.out.println(e);
    }
    driver.findElement(By.id("mat-form:nuevoIng")).click();
    try {
        Thread.sleep(3000);
    } catch (Exception e) {
        System.out.println(e);
    }
    driver.findElement(By.id("mat-form:sendMatricula")).click();
    driver.findElement(By.id("form:matriculado")).click();
    driver.findElement(By.id("form:search")).click();
    try {
        Thread.sleep(7000);
    } catch (Exception e) {
        System.out.println(e);
    }
    driver.findElement(By.id("matriculas:0:_mat")).click();
    try {
        Thread.sleep(7000);
    } catch (Exception e) {
        System.out.println(e);
    }
    {
      String value = driver.findElement(By.id("mat-form:nuevoIng")).getAttribute("value");
      assertThat(value, is("on"));
    }
    driver.findElement(By.id("mat-form:nuevoIng")).click();
    driver.findElement(By.id("mat-form:sendMatricula")).click();
  }
}
