// Generated by Selenium IDE
import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class PruebaImportacionIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver","./src/test/resources/drivers/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    //driver.quit();
  }
  @Test
  public void prueba() {
    driver.get("http://localhost:8080/ProyectoWAR/");
    driver.manage().window().maximize();
    driver.findElement(By.linkText("Importar")).click();
    driver.findElement(By.cssSelector("#j_idt7\\3A Alumnos")).click();
    driver.findElement(By.cssSelector("#j_idt7\\3A Alumnos")).sendKeys("C:\\fakepath\\alumnos.xlsx");
    driver.findElement(By.id("j_idt7:titulaciones")).click();
    driver.findElement(By.cssSelector("#j_idt7\\3Atitulaciones")).sendKeys("C:\\fakepath\\Titulacion.xlsx");
    driver.findElement(By.id("j_idt7:Asignaturas")).click();
    driver.findElement(By.cssSelector("#j_idt7\\3A Asignaturas")).sendKeys("C:\\fakepath\\Oferta asignaturas.xlsx");
    driver.findElement(By.id("j_idt7:submit")).click();
  }
}