// Generated by Selenium IDE
import java.io.File;
import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class PruebaImportacionIT {
  private WebDriver driver;
  JavascriptExecutor js;
  
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver","./src/test/resources/drivers/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    //driver.quit();
  }
  @Test
  public void importarIT() {
	File alumnos = new File("D:\\Universidad - Informática\\Tercero\\Sistemas de Información para Internet X\\Trabajo\\Tarea 3\\WORKSPACE\\Proyecto-SII\\DATOS\\alumnos.xlsx");  
	String pathalumnos = alumnos.getAbsolutePath();
	//File titulaciones = new File("\\Proyecto-SII\\DATOS\\Titulacion.xlsx");  
	//String pathtitulaciones = alumnos.getAbsolutePath();
	//File asignaturas = new File("\\Proyecto-SII\\DATOS\\Oferta_asignaturas.xlsx");  
	//String pathasignaturas = alumnos.getAbsolutePath();
	  
    driver.get("http://localhost:8080/ProyectoWAR/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.linkText("Importar")).click();
    driver.findElement(By.id("j_idt7:Alumnos")).click();
    driver.findElement(By.id("j_idt7:Alumnos")).sendKeys("C:\\Users\\Efrain\\Desktop\\sii\\alumnos.xlsx");
    //driver.findElement(By.id("j_idt7:titulaciones")).click();
    //driver.findElement(By.id("j_idt7:titulaciones")).sendKeys("C:\\fakepath\\Titulacion.xlsx");
    //driver.findElement(By.id("j_idt7:Asignaturas")).click();
    //driver.findElement(By.id("j_idt7:Asignaturas")).sendKeys("C:\\fakepath\\Oferta asignaturas.xlsx");
    driver.findElement(By.id("j_idt7:submit")).click();
    driver.findElement(By.linkText("Home")).click();
    //driver.findElement(By.id("form:name")).click();
    //driver.findElement(By.id("form:name")).click();
    //driver.findElement(By.id("form:name")).sendKeys("Rocco");
    //driver.findElement(By.cssSelector(".w3-half:nth-child(2) > .form-label")).click();
    //driver.findElement(By.id("form:search")).click();
  }
}
